"""The client's side of the protocol-module contract: interfaces, shared types, errors, registry."""

from .api import Association, ConnectionDiagnosis, ControlObject, FailedAssociation, Naming, ProtocolModule
from .errors import ConnectError, EncodeError, NotConnectedError, ProtocolError, ServiceError
from .registry import DEFAULT_PROTOCOL, UnknownProtocolError, available, get, load_all, register, unregister
from .types import (
    RCB_WRITABLE,
    AccessError,
    BinaryTime,
    BitString,
    CommandTermination,
    ControlStepResult,
    DataSetMember,
    DatasetRef,
    FileEntry,
    RawValue,
    RcbValues,
    Report,
    ReportEntry,
    ServerIdentity,
    UtcTime,
    Value,
    ValueKind,
    VarSpec,
    format_value,
    value_from_json,
    value_to_json,
)
from .values import coerce, parse_text

__all__ = [
    "DEFAULT_PROTOCOL",
    "RCB_WRITABLE",
    "AccessError",
    "Association",
    "BinaryTime",
    "BitString",
    "CommandTermination",
    "ConnectError",
    "ConnectionDiagnosis",
    "ControlObject",
    "ControlStepResult",
    "DataSetMember",
    "DatasetRef",
    "EncodeError",
    "FailedAssociation",
    "FileEntry",
    "Naming",
    "NotConnectedError",
    "ProtocolError",
    "ProtocolModule",
    "RawValue",
    "RcbValues",
    "Report",
    "ReportEntry",
    "ServerIdentity",
    "ServiceError",
    "UnknownProtocolError",
    "UtcTime",
    "Value",
    "ValueKind",
    "VarSpec",
    "available",
    "coerce",
    "format_value",
    "get",
    "load_all",
    "parse_text",
    "register",
    "unregister",
    "value_from_json",
    "value_to_json",
]
